### ISSUE TITLE
Hello, Author of the code!

### ISSUE THREAD

**Issue by va1ngvarr** [Ankitsinghprograms/search_web#2]
I just found this library out of the Internet, I was overflowed by hope that it really works well, but somehow, when I use it, nothing's been happened with any function :(
![image](https://github.com/Ankitsinghprograms/search_web/assets/93223722/0f146d08-ff9c-4f5a-b1b2-da2e6a0e6e8c)

**Comment by Ankitsinghprograms** [comment]
Don't use print it will automatically opens your default browser using Web-brwoser module
 This is not web scrapping module.
